### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by radiophonic** [qedjoe/tweet-parser#2]
Greetings.

I'm not certain if you're still developing this tool or not, however it's the only one of its kind that I've found so I wanted to say thank you.

I have an issue, however. It would appear that the program can't find the DejaSans font. I created a folder in its directory and placed your recommended font inside of it from the repository but it still refuses to work. I also ran it with the --font argument pointing to the font file itself but no luck.

If you are willing, maybe you could look into this or, if you know of a different way to convert these twitter json files to something readable I would appreciate it.

Thanks and take care.

```
tweets2pdf -f tweet.json -p test.pfg
Traceback (most recent call last):
  File "/home/snafu/.local/bin/tweets2pdf", line 8, in <module>
    sys.exit(main())
  File "/home/snafu/.local/lib/python3.10/site-packages/tweets2pdf/__main__.py", line 76, in main
    pdf = PDFDocument(font=options.font, font_family=options.font_family, font_size=options.font_size)
  File "/home/snafu/.local/lib/python3.10/site-packages/tweets2pdf/pdf.py", line 32, in __init__
    self.pdf.add_font(family=self.font_family, style=self.style, fname=self.font, uni=True)
  File "/home/snafu/.local/lib/python3.10/site-packages/fpdf/fpdf.py", line 469, in add_font
    raise RuntimeError("TTF Font file not found: %s" % fname)
RuntimeError: TTF Font file not found: font/DejaVuSans.ttf
```

**Comment by qedjoe** [comment]
Hi @radiophonic, thanks for getting in touch. No, I'm afraid that I'm not working on this tool currently. Ah, I'm sorry it doesn't load the file TTF file correctly.

I'd be happy to fix this when I have time. I need to [include the font](https://packaging.python.org/en/latest/tutorials/packaging-projects/#including-other-files) in this Python package and made it load that font file using [importlib.resources](https://docs.python.org/3/library/importlib.resources.html).

As a workaround, try this:

1. Download the DejaVu Sans font file (DejaVuSans.ttf) from https://dejavu-fonts.github.io/
2. Save the file in your home directory at `~/DejaVuSans.ttf`
3. Run the `tweet2pdf` tool using the `--font` option like so:

```bash
tweets2pdf --font ~/DejaVuSans.ttf --file test.json  --pdf output.pdf
```

**Comment by radiophonic** [comment]
Hello, thanks for the response.

Yeah, I hacked around a bit and tried some different methods as you suggested but nothing seems to take. 

It's not of any major importance, so I'll wait until you have the time to mess around with it. 

Have a good one!
